// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using My.DAL.Data;

#nullable disable

namespace My.DAL.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260630173327_AddStopwatchItems")]
    partial class AddStopwatchItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("My.DAL.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Key = "AllowUserDelete",
                            Description = "Allow administrators to delete users",
                            Value = "false"
                        },
                        new
                        {
                            Key = "DataRetentionDays",
                            Description = "Days of data retention before a user can be deleted",
                            Value = "2555"
                        },
                        new
                        {
                            Key = "AllowOrganizationDelete",
                            Description = "Allow managers to delete organizations",
                            Value = "false"
                        },
                        new
                        {
                            Key = "AllowProjectDelete",
                            Description = "Allow managers to delete projects",
                            Value = "false"
                        },
                        new
                        {
                            Key = "TymeSubmissionMonthInterval",
                            Description = "How often (in months) employees are expected to submit their time.",
                            Value = "1"
                        },
                        new
                        {
                            Key = "TymeCalendarBackfillDefaultDays",
                            Description = "Default lookback window (in days) when pushing existing tracked tasks onto a newly-connected user's primary Google calendar.",
                            Value = "30"
                        },
                        new
                        {
                            Key = "TymeCalendarBackfillPromptUser",
                            Description = "When true, users are prompted to choose a date range (or skip) on connect. When false, the default lookback above is applied silently.",
                            Value = "true"
                        },
                        new
                        {
                            Key = "WorkdayHours",
                            Description = "How many hours count as a full workday. Drives the derived Duration for all-day entries (Vacation/OOO).",
                            Value = "8"
                        },
                        new
                        {
                            Key = "TeamAvailabilityCalendarId",
                            Description = "Google calendar id of the workspace-shared 'Team Availability' calendar. Empty disables the team-availability dual-publish feature.",
                            Value = ""
                        });
                });

            modelBuilder.Entity("My.DAL.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d1e2f3a4-b5c6-7890-d1e2-f3a4b5c67890",
                            ConcurrencyStamp = "d1e2f3a4-b5c6-7890-d1e2-f3a4b5c67890",
                            Description = "Basic role with lowest rights.",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "6dec8b09-9fa0-474b-ae23-b4267c2c516a",
                            ConcurrencyStamp = "6dec8b09-9fa0-474b-ae23-b4267c2c516a",
                            Description = "Admin role with highest rights.",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "f72e9c7c-2517-427b-b08b-56966c51f5d4",
                            ConcurrencyStamp = "f72e9c7c-2517-427b-b08b-56966c51f5d4",
                            Description = "Manager role for for users and reports",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "a1b2c3d4-e5f6-7890-a1b2-c3d4e5f67890",
                            ConcurrencyStamp = "a1b2c3d4-e5f6-7890-a1b2-c3d4e5f67890",
                            Description = "Tyme-scoped basic user role.",
                            Name = "User:Tyme",
                            NormalizedName = "USER:TYME"
                        },
                        new
                        {
                            Id = "b2c3d4e5-f6a7-8901-b2c3-d4e5f6a78901",
                            ConcurrencyStamp = "b2c3d4e5-f6a7-8901-b2c3-d4e5f6a78901",
                            Description = "Tyme-scoped manager role.",
                            Name = "Manager:Tyme",
                            NormalizedName = "MANAGER:TYME"
                        },
                        new
                        {
                            Id = "c3d4e5f6-a7b8-9012-c3d4-e5f6a7b89012",
                            ConcurrencyStamp = "c3d4e5f6-a7b8-9012-c3d4-e5f6a7b89012",
                            Description = "Tyme-scoped admin role.",
                            Name = "Admin:Tyme",
                            NormalizedName = "ADMIN:TYME"
                        },
                        new
                        {
                            Id = "d4e5f6a7-b8c9-0123-d4e5-f6a7b8c90123",
                            ConcurrencyStamp = "d4e5f6a7-b8c9-0123-d4e5-f6a7b8c90123",
                            Description = "Intranet-scoped basic user role (view published pages and curated navigation).",
                            Name = "User:Intranet",
                            NormalizedName = "USER:INTRANET"
                        },
                        new
                        {
                            Id = "e5f6a7b8-c9d0-1234-e5f6-a7b8c9d01234",
                            ConcurrencyStamp = "e5f6a7b8-c9d0-1234-e5f6-a7b8c9d01234",
                            Description = "Intranet-scoped editor role (create/edit pages and manage documents).",
                            Name = "Editor:Intranet",
                            NormalizedName = "EDITOR:INTRANET"
                        },
                        new
                        {
                            Id = "f6a7b8c9-d0e1-2345-f6a7-b8c9d0e12345",
                            ConcurrencyStamp = "f6a7b8c9-d0e1-2345-f6a7-b8c9d0e12345",
                            Description = "Intranet-scoped admin role (full control of navigation structure and content).",
                            Name = "Admin:Intranet",
                            NormalizedName = "ADMIN:INTRANET"
                        });
                });

            modelBuilder.Entity("My.DAL.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("LastSignInAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("OidcSessionInvalidatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("My.DAL.Models.Contact", b =>
                {
                    b.Property<string>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ContactId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("My.DAL.Models.Department", b =>
                {
                    b.Property<string>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("My.DAL.Models.IntranetDocument", b =>
                {
                    b.Property<string>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriveFileId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DriveLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriveOwnerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriveOwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThumbnailLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebViewLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentId");

                    b.HasIndex("DriveFileId")
                        .IsUnique()
                        .HasDatabaseName("IX_IntranetDocuments_DriveFileId");

                    b.ToTable("IntranetDocuments");
                });

            modelBuilder.Entity("My.DAL.Models.IntranetNavigationItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("PageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.HasIndex("ParentId");

                    b.ToTable("IntranetNavigationItems");
                });

            modelBuilder.Entity("My.DAL.Models.IntranetPage", b =>
                {
                    b.Property<string>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContentMarkdown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("ParentPageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("RestrictEditingToOwner")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Default");

                    b.HasKey("PageId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ParentPageId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_IntranetPages_Slug")
                        .HasFilter("[Slug] IS NOT NULL");

                    b.ToTable("IntranetPages");
                });

            modelBuilder.Entity("My.DAL.Models.IntranetPageDocument", b =>
                {
                    b.Property<string>("PageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocumentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Caption")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("PageId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("IntranetPageDocuments");
                });

            modelBuilder.Entity("My.DAL.Models.Organization", b =>
                {
                    b.Property<string>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrganizationId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("My.DAL.Models.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSharedAvailability")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectGroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Slug")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("ProjectId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectGroupId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Projects_Slug")
                        .HasFilter("[Slug] IS NOT NULL");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("My.DAL.Models.ProjectGroup", b =>
                {
                    b.Property<string>("ProjectGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProjectGroupId");

                    b.ToTable("ProjectGroups");
                });

            modelBuilder.Entity("My.DAL.Models.StopwatchItem", b =>
                {
                    b.Property<string>("StopwatchItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastWorkedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StopwatchItemId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId", "LastWorkedAt");

                    b.ToTable("StopwatchItems");
                });

            modelBuilder.Entity("My.DAL.Models.TimeSubmission", b =>
                {
                    b.Property<string>("TimeSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmittedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("TimeSubmissionId");

                    b.HasIndex("UserId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("TimeSubmissions");
                });

            modelBuilder.Entity("My.DAL.Models.TrackedTask", b =>
                {
                    b.Property<string>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleEventId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StopwatchItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TeamAvailabilityEventId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TaskId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StopwatchItemId", "StartDate");

                    b.HasIndex("UserId", "StartDate");

                    b.ToTable("TrackedTasks");
                });

            modelBuilder.Entity("My.DAL.Models.TrackedTaskAlias", b =>
                {
                    b.Property<string>("TrackedTaskAliasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TrackedTaskAliasId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.ToTable("TrackedTaskAliases");
                });

            modelBuilder.Entity("My.DAL.Models.UserSettings", b =>
                {
                    b.Property<string>("UserSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CalendarBackfillAcknowledgedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FavoriteIntranetPageIdsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleCalendarEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleCalendarId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GoogleChannelExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleChannelId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleRefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleResourceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleSyncToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ImportFromGoogleCalendar")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectColorSource")
                        .HasColumnType("int");

                    b.Property<bool>("PublishToGoogleCalendar")
                        .HasColumnType("bit");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TymeEventColorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TymeUnmatchedEventColorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Use24HourTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserSettingsId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("My.DAL.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("My.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("My.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("My.DAL.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("My.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("My.DAL.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("My.DAL.Models.Contact", b =>
                {
                    b.HasOne("My.DAL.Models.Department", "Department")
                        .WithMany("Contacts")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("My.DAL.Models.Organization", "Organization")
                        .WithMany("Contacts")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Department");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("My.DAL.Models.Department", b =>
                {
                    b.HasOne("My.DAL.Models.Organization", "Organization")
                        .WithMany("Departments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("My.DAL.Models.IntranetNavigationItem", b =>
                {
                    b.HasOne("My.DAL.Models.IntranetPage", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("My.DAL.Models.IntranetNavigationItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Page");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("My.DAL.Models.IntranetPage", b =>
                {
                    b.HasOne("My.DAL.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("My.DAL.Models.IntranetPage", "ParentPage")
                        .WithMany("ChildPages")
                        .HasForeignKey("ParentPageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("ParentPage");
                });

            modelBuilder.Entity("My.DAL.Models.IntranetPageDocument", b =>
                {
                    b.HasOne("My.DAL.Models.IntranetDocument", "Document")
                        .WithMany("PageDocuments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("My.DAL.Models.IntranetPage", "Page")
                        .WithMany("PageDocuments")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("My.DAL.Models.Project", b =>
                {
                    b.HasOne("My.DAL.Models.Department", "Department")
                        .WithMany("Projects")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("My.DAL.Models.Organization", "Organization")
                        .WithMany("Projects")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("My.DAL.Models.ProjectGroup", "ProjectGroup")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Organization");

                    b.Navigation("ProjectGroup");
                });

            modelBuilder.Entity("My.DAL.Models.StopwatchItem", b =>
                {
                    b.HasOne("My.DAL.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("My.DAL.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.DAL.Models.TimeSubmission", b =>
                {
                    b.HasOne("My.DAL.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.DAL.Models.TrackedTask", b =>
                {
                    b.HasOne("My.DAL.Models.Project", "Project")
                        .WithMany("TrackedTasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("My.DAL.Models.StopwatchItem", "StopwatchItem")
                        .WithMany("Sessions")
                        .HasForeignKey("StopwatchItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("My.DAL.Models.ApplicationUser", "User")
                        .WithMany("TrackedTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("StopwatchItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.DAL.Models.TrackedTaskAlias", b =>
                {
                    b.HasOne("My.DAL.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("My.DAL.Models.TrackedTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("My.DAL.Models.UserSettings", b =>
                {
                    b.HasOne("My.DAL.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("My.DAL.Models.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("My.DAL.Models.ApplicationUser", b =>
                {
                    b.Navigation("TrackedTasks");
                });

            modelBuilder.Entity("My.DAL.Models.Department", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("My.DAL.Models.IntranetDocument", b =>
                {
                    b.Navigation("PageDocuments");
                });

            modelBuilder.Entity("My.DAL.Models.IntranetNavigationItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("My.DAL.Models.IntranetPage", b =>
                {
                    b.Navigation("ChildPages");

                    b.Navigation("PageDocuments");
                });

            modelBuilder.Entity("My.DAL.Models.Organization", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Departments");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("My.DAL.Models.Project", b =>
                {
                    b.Navigation("TrackedTasks");
                });

            modelBuilder.Entity("My.DAL.Models.ProjectGroup", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("My.DAL.Models.StopwatchItem", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
